### ISSUE TITLE
Doesn't generate excel file as expected but no obvious error

### ISSUE THREAD

**Issue by mdivk** [ZuInnoTe/spark-hadoopoffice-ds#20]
Start spark2-shell with the library:
`spark2-shell --packages com.github.zuinnote:spark-hadoopoffice-ds_2.12:1.2.4`

Run the following code and get the result beneath the code:
````
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.2.0.cloudera1
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> val q = "select * from branch_grouped_by_month"
q: String = select * from branch_grouped_by_month

scala> val df = spark.sql(q)
df: org.apache.spark.sql.DataFrame = [branch_id: string, dist_accts: bigint ... 1 more field]

scala> df.show()
+---------+----------+-----------------+
|branch_id|dist_accts|              _c2|
+---------+----------+-----------------+
|   001659|         1|          4536.45|
|   880700|         1|           646.94|
|   008754|         2|             15.5|
|   008820|         2|          4329.82|
|   880565|         1|              0.0|
|   001746|         1|           454.13|
|   800415|         1|              0.0|
|   800202|         1|              0.0|
|   101029|         1|              0.0|
|   880694|         1|           681.63|
|   060022|         1|           909.34|
|   800284|         1|          1862.48|
|   001241|         1|          9171.86|
|   880573|         2|           1729.8|
|   001780|         1|            -0.79|
|   060700|         1|           866.01|
|   800421|         2|8154.120000000001|
|   001137|         1|              0.0|
|   060043|         1|              0.0|
|   060001|         2|          3499.45|
+---------+----------+-----------------+
only showing top 20 rows


scala> df.write.format("org.zuinnote.spark.office.excel").option("spark.write.useHeader",true).option("write.locale.bcp47", "us").save("gaps.xlsx");
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.FileFormat.$init$(Lorg/apache/spark/sql/execution/datasources/FileFormat;)V
  at org.zuinnote.spark.office.excel.DefaultSource.<init>(DefaultSource.scala:115)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:470)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
  ... 50 elided

scala>
```
What am I missing here? Can anyone please help me to sort it out? Thank you very much in advance.

**Comment by jornfranke** [comment]
Yes you are using the Scala 2.12 version of the data source, but your Spark is based on Scala 2.11. Just use the 2.11 version of the data source and you should be fine.

Spark supports Scala 2.12 only as of 2.4.

For the functionality of the data source it makes no difference.

**Comment by jornfranke** [comment]
Did it work out for you?

**Comment by jornfranke** [comment]
Please create a new issue if this is still a problem
