### ISSUE TITLE
IndexOutOfBoundsException:  When reading xlsx file.

### ISSUE THREAD

**Issue by ABanerji** [ZuInnoTe/spark-hadoopoffice-ds#24]
Hi,

I'm getting IndexOutOfBoundsException when trying to read an xlsx file. The testing.xlsx which comes as a part of this library works file but not the one which I'm using. Not sure if this is Spark's issue. I'm using pyspark for the coding.

**System Config:** 
1. Spark : 2.3.3
2. spark-hadoopoffice-ds: V1.3.0
3. Scala: 2.11.8

**Code Snippet:**

df_RPM = spark.read.format('org.zuinnote.spark.office.excel') \
       .option("read.locale.bcp47", "us") \
       .option("read.spark.simpleMode", "true") \
       .option("hadoopoffice.read.header.read", "true") \
       .option("hadoopoffice.read.lowFootprint", "true") \
       .load(r'D:\IDD\data\iDD\Sample.xlsx')

**Excel File**
[Sample.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/3158231/Sample.xlsx)

**Exception:**

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-11-35b0b563fc11> in <module>
      4        .option("hadoopoffice.read.header.read", "true") \
      5        .option("hadoopoffice.read.lowFootprint", "true") \
----> 6        .load(r'D:\IDD\data\iDD\Sample.xlsx')

D:\Spark\spark-2.3.3-bin-hadoop2.7\python\pyspark\sql\readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

D:\Spark\spark-2.3.3-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

D:\Spark\spark-2.3.3-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

D:\Spark\spark-2.3.3-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o232.load.
: java.lang.IndexOutOfBoundsException: 15
	at scala.collection.mutable.ListBuffer.update(ListBuffer.scala:139)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$inferSchema$4.apply(DefaultSource.scala:211)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$inferSchema$4.apply(DefaultSource.scala:188)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.zuinnote.spark.office.excel.DefaultSource.inferSchema(DefaultSource.scala:188)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:202)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:393)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jornfranke** [comment]
It could be that it is due to the last column, which does not contain data. As a workaround you could deactivate infering the schema and define a manual schema. Alternatively you could delete the last column or fill it with data. I will do some further investigations to see if a fix is needed

**Comment by jornfranke** [comment]
Hmm I tried to reproduce this error, but was not successful yet. I don't have a Windows Spark system though. I will continue to try.

May I ask which Excel version are you using to create this file?

**Comment by ABanerji** [comment]
I'm not sure on version of Excel used. This Excel is actually a part of export to Excel functionality present on portal. I will try deleting the last column and post the results. Thanks for looking into it.

**Comment by ABanerji** [comment]
> It could be that it is due to the last column, which does not contain data. As a workaround you could deactivate infering the schema and define a manual schema. Alternatively you could delete the last column or fill it with data. I will do some further investigations to see if a fix is needed

I tried deleting several empty columns but this still remains the same error.

**Comment by jornfranke** [comment]
I pushed a fix to the repo. I will start publishing it.

**Comment by jornfranke** [comment]
published 1.3.1 can you please check?

**Comment by ABanerji** [comment]
> published 1.3.1 can you please check?

Thanks for working on this in such a short time span. I will check and let you know.

**Comment by ABanerji** [comment]
This is working seamlessly now. I'm closing this issue. Thanks once again.
