### ISSUE TITLE
workbookDocument .getWorkbook().getWorkbookPr() can return null

### ISSUE THREAD

**Issue by Pooj2** [ZuInnoTe/spark-hadoopoffice-ds#28]
In org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.class v1.3.3 the following lines gives me a NullPointerException:
			`WorkbookDocument wd = WorkbookDocument.Factory.parse(workbookDataXML);
			this.isDate1904 = wd.getWorkbook().getWorkbookPr().getDate1904();`

cause workbookDocument .getWorkbook().getWorkbookPr() can return null.
For fix see example https://github.com/alibaba/easyexcel/blob/master/src/main/java/com/alibaba/excel/analysis/v07/XlsxSaxAnalyser.java#L40

Unfortunately, I am not allowed to distribute any of the spreadsheets that fail.

Stacktrace:
12:57:44,174 ERROR [rker for task 0] org.apache.spark.executor.Executor.logError: Exception in task 0.0 in stage 0.0 (TID 0)            line: org.apache.spark.internal.Logging$class.logError(Logging.scala:91)
java.lang.NullPointerException
	at org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.processOPCPackage(MSExcelLowFootprintParser.java:349)
	at org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.parse(MSExcelLowFootprintParser.java:267)
	at org.zuinnote.hadoop.office.format.common.OfficeReader.parse(OfficeReader.java:92)
	at org.zuinnote.hadoop.office.format.mapreduce.AbstractSpreadSheetDocumentRecordReader.initialize(AbstractSpreadSheetDocumentRecordReader.java:138)
	at org.zuinnote.spark.office.excel.HadoopFileExcelReader.<init>(HadoopFileExcelReader.scala:55)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$3.apply(DefaultSource.scala:317)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$3.apply(DefaultSource.scala:312)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:138)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:122)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:168)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jornfranke** [comment]
Ok thanks for reporting I will look into it

**Comment by jornfranke** [comment]
Can you maybe share the issue in the Excel file ? Ie not the full Excel file, but why this occurs? So I can write a unit test to reproduce it

**Comment by jornfranke** [comment]
I will release the fix on the weekend as part of 1.3.5, unfortunately i cannot test it, but it should be simple enough

**Comment by Pooj2** [comment]
Unfortunately, I am not allowed to distribute any of the spreadsheets that fail.

The spreadsheets that fail have a ./xl/workbook.xml like `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Blad1" sheetId="1" r:id="rId1"/></sheets></workbook>`

I have to manipulate a spreadsheet to get a workbook.xml like above, cause one made myself (like the attached one) has a workbook.xml with much more 2011 elements. Due to firewalls I can not upload a manipulated spreadsheet, but here is a recipe to reproduce:
1. unzip the attached spreadsheet to a folder;
2. cd to created folder;
3. change the content of ./xl/workbook.xml into  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Blad1" sheetId="1" r:id="rId1"/></sheets></workbook>`
4. zip -r -D ../MapIssue28b.xlsx *
5. compare the spreadsheets with unzip -l; the containing filenames should be the same;
6. MapIssue28**b**.xlsx is now the spreadsheet that fails while Low footprint parsing with `07:57:58,871 INFO  [rker for task 0] format.common.parser.msexcel.MSExcelLowFootprintParser.parse: Low footprint parsing of new Excel files (.xlsx) - not encrypted file            line: org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.parse(MSExcelLowFootprintParser.java:261)
07:57:59,317 ERROR [rker for task 0] org.apache.spark.executor.Executor.logError: Exception in task 0.0 in stage 0.0 (TID 0)            line: org.apache.spark.internal.Logging$class.logError(Logging.scala:91)
java.lang.NullPointerException
	at org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.processOPCPackage(MSExcelLowFootprintParser.java:349)
	at org.zuinnote.hadoop.office.format.common.parser.msexcel.MSExcelLowFootprintParser.parse(MSExcelLowFootprintParser.java:267)`

When using standard API to parse Excel file you get a result like `08:02:37,192 INFO  [rker for task 5] hadoop.office.format.common.OfficeReader.parse: Using standard API to parse Excel file            line: org.zuinnote.hadoop.office.format.common.OfficeReader.parse(OfficeReader.java:79)
08:02:37,252 INFO  [main] politie.bvi.xls.job.XlsSrcToArchiveLoaderSparkJobIntegrationTest.testIssue28FilesLowFootPrintFailBVILT8304: /XLSX/MapIssue28b.xlsx schema converted: root
 |-- Head1: string (nullable = true)
 |-- Head2: string (nullable = true)
 |-- Head3: string (nullable = true)
, top:
+-----+------+------+
|Head1|Head2 |Head3 |
+-----+------+------+
|key1 |datac3|datad1|
|key2 |datac4|datad2|
+-----+------+------+`

Ps. log4j
`log4j.appender.console.layout.ConversionPattern=%d{HH:mm:ss,SSS} %-5p [%.15t] %c{5}.%M: %m            line: %l%n
[MapIssue28.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/3792491/MapIssue28.xlsx)
`

**Comment by jornfranke** [comment]
Thanks! I think I will publish v 1.3.5 next weekend

Thank you for the detailed report

**Comment by jornfranke** [comment]
I published a fix with version 1.3.5 - can you please verify if the bug is fixed?
thank you.

**Comment by Pooj2** [comment]
Fixed, thnx! 

The bug described as above is fixed in v1.3.5.

**Comment by jornfranke** [comment]
thank you for the feedback and detailled report
